### ISSUE TITLE
CM1223 footprint incorrect

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#10]
SOT143-4 footprint is used:

![image](https://user-images.githubusercontent.com/1595938/193407774-36412144-ff29-4a5a-91b9-6b63afc235b7.png)

Correct CM1223-**02SO** package is SOT23−5:

![image](https://user-images.githubusercontent.com/1595938/193407816-22a789a8-a404-41bd-bb37-3fd2a4c4545a.png)
![image](https://user-images.githubusercontent.com/1595938/193407803-ce9e0b4f-0c41-41c0-91d1-3c0c944ac84c.png)

This is also mentioned on [Components page](https://ut-robotics.github.io/picr22-home/basketball_robot_guide/electronics/components.html#_usb_protection).

**Comment by AnishShr** [comment]
Changed the footprint with correct one.
