### ISSUE TITLE
NCP164CSN330T1G does not need feedback resistors

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#11]
NCP164CSN330T1G has fixed output of 3.3V (V<sub>FIX</sub>).

Feedback resistors can technically be used, but would probably not work if reference voltage is the same or higher compared to output voltage.

From [datasheet](https://www.onsemi.com/pdf/datasheet/ncp164-d.pdf):
![image](https://user-images.githubusercontent.com/1595938/193408486-e4bd1e2c-5387-4907-a2f2-e4840d35caac.png)

**Comment by AnishShr** [comment]
Feedback resistors removed.
