### ISSUE TITLE
NCP164 enable pin needs to be connected

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#12]
I think NCP164 has weak pull-down on enable (EN) pin that disables the regulator when enable pin is left unconnected:

![image](https://user-images.githubusercontent.com/1595938/193408874-e005a975-4d74-4cd0-bec9-079712b0071c.png)

![image](https://user-images.githubusercontent.com/1595938/193408720-d5eb8416-a90a-407d-b7a5-f0845856985d.png)

Enable pin can be connected to IN pin to enable the regulator.

**Comment by AnishShr** [comment]
connected the EN pin to IN.
