### ISSUE TITLE
NCV8730ASN500T1G does not need feedback resistors

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#13]
NCV8730ASN500T1G has fixed output of 5V.

From [datasheet](https://www.onsemi.com/pdf/datasheet/ncv8730-d.pdf):
![image](https://user-images.githubusercontent.com/1595938/193409324-a4b65fdf-3676-496d-91fb-7d396062a93a.png)

**Comment by AnishShr** [comment]
Feedback resistors removed.
