### ISSUE TITLE
3.3V is not needed on motor drivers side

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#14]
![image](https://user-images.githubusercontent.com/1595938/193409413-cbcc4c51-7d8b-40dc-9dc7-020577793dcc.png)

Isolators can be powered from 5V:
![image](https://user-images.githubusercontent.com/1595938/193409464-5c41051e-4aef-4a3d-8b49-5ed4bbc664dc.png)

**Comment by AnishShr** [comment]
removed the 3.3V converter in the battery side
