### ISSUE TITLE
Incorrect encoder connector pinout

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#15]
![image](https://user-images.githubusercontent.com/1595938/193409709-d4b70cdd-489c-4d8d-bda5-821baae40338.png)

All existing encoders use this pinout:

1. GND
2. 3.3V
3. ENCA
4. ENCB

Power needs to be connected. Right now it has not been connected.

GND needs to be connected to MCU side. Right now it's connected to motor drivers side (GND2).
Encoders and motors are not electrically connected, only mechanically

**Comment by AnishShr** [comment]
Connector with correct wire orientation updated.

**Comment by ReikoR** [comment]
Avoid placing GND symbols pointing up. 
![image](https://user-images.githubusercontent.com/1595938/193895781-18aa249e-46c5-48d8-a2a6-0adc1b47604c.png)

GND should point down and positive power symbols should point up. It would be nicer to use power symbols for them not the net labels.
![image](https://user-images.githubusercontent.com/1595938/193895561-b51650c7-cd0d-4217-965a-ebd1cca06eb8.png)


Encoder connectors are still connected to GND2. Encoders need to be connected to MCU GND.

**Comment by AnishShr** [comment]
changed the symbol orientations accordingly.
