### ISSUE TITLE
nFAULT LEDs not connected correctly

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#17]
DRV8243 nFAULT pins are open drain outputs.

For LEDs to work, they need be connected to logic voltage (5V in this case).

More information:
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/electronics/schematic.html#_open_drain_outputs

**Comment by AnishShr** [comment]
LEDs removed from the nFAULT lines.

**Comment by ReikoR** [comment]
LEDs can still be used, but have to be connected differently.
