### ISSUE TITLE
PDRV8243HRXYQ1 does not have SPI

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#18]
![image](https://user-images.githubusercontent.com/1595938/193411746-70a2f892-8bca-44da-9f8a-69e99344191a.png)

DRV8243 drivers we have are the HW variant in VQFN-HR (14) package.

**Comment by AnishShr** [comment]
Symbol and footprint with VQFN-HR(14) variant updated

**Comment by ReikoR** [comment]
All configuration pins cannot be left unconnected.
![image](https://user-images.githubusercontent.com/1595938/193900811-1b5bebab-5741-44e2-917b-bc27ee6f4143.png)

**IPROPI** pin needs a resistor to set the output current limit. I recommend configuring current limit to around 2 - 3A to help prevent motor from overheating.
![image](https://user-images.githubusercontent.com/1595938/193904314-ae933790-3061-4744-b750-cc009d656274.png)

**DRVOFF** need to be connected to ground, otherwise the outputs will be disabled. DRVOFF has internal pullup.
![image](https://user-images.githubusercontent.com/1595938/193902758-cf46df8b-a258-4827-bea5-f4e61ca98f85.png)

**DIAG** pin I would recommend connecting to GND to allow the driver to enable the outputs again after a small off period (t<sub>off</sub>). This allows for higher motor power, but it might be ok without it also.
![image](https://user-images.githubusercontent.com/1595938/193904068-b718102f-b1e8-4e1b-91d3-54d62efd0186.png)
![image](https://user-images.githubusercontent.com/1595938/193904276-d1bfa83c-f30c-4edf-9f4e-1367b7019bc0.png)

**MODE** pin needs to be connected to set the driver to PH/EN (PWM/direction) mode.
![image](https://user-images.githubusercontent.com/1595938/193903210-6070535f-185c-46c7-9462-1dac359265ce.png)



I added older datasheet that contains pre-production driver information to the components page:
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/electronics/components.html#_motor_driver

**Comment by AnishShr** [comment]
According to the datasheet:   
For the VQFN-HR package, AIPROPI = 3070 A/A   
We are operating the HW variant in RLVL6of6 for ITRIP, SR, and DIAG, meaning not connecting those pins.   
For this config, VITRIP = 2.97 V   
For this configuration:   
ITRIP Regulation = VITRIP / RITRIP * AIPROPI   
This yields RITRIP approximately to 3040 Ohms. What will be the closest resistance we have in the 0603 package to this resistance?
<img width="533" alt="AIPROPI" src="https://user-images.githubusercontent.com/62991158/194233349-63443080-1c58-4bd5-b3de-d82bc06cdc85.PNG">
<img width="525" alt="HW variant" src="https://user-images.githubusercontent.com/62991158/194233355-3d6dff83-9a63-4c65-827e-8c0246c57a66.PNG">
<img width="528" alt="VITRIP" src="https://user-images.githubusercontent.com/62991158/194233358-ea1b4fba-0353-4ce6-89ee-c581ecf79450.PNG">

**Comment by ReikoR** [comment]
You might have already checked yourself, but in the lab we have 3k and also 2.7k and 3.3k 0603 resistors.

**Comment by AnishShr** [comment]
Connected all other pins as instructed in the datasheet.
