### ISSUE TITLE
DRV8243 VM pins need more capacitance

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#19]
![image](https://user-images.githubusercontent.com/1595938/193411996-4dd5c3d8-9ca7-4a8d-be32-3b1c7e4d01c5.png)

More capacitance is needed during switching at driver's input (VM) to avoid voltage drop at the driver's output.
Around 50 uF or more might be fine. For example it's possible to use 5x 10 uF ceramic capacitors.

**Comment by AnishShr** [comment]
50uF capacitance put across the Vm pin.

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/193906971-86ba6ee4-cc59-4f03-9f5a-c2d1a6b60995.png)

50uF 0603 capacitors do not exist.

For example 47uF 25V capacitors are much bigger and expensive:
https://www.mouser.ee/c/passive-components/capacitors/mlccs/multilayer-ceramic-capacitors-mlcc-smd-smt/?capacitance=47%20uF&voltage%20rating%20dc=25%20VDC&instock=y&sort=pricing

Using 5x 10 uF 1206 25V+ capacitors or similar is better option.

Typical recommendation is to use capacitors with voltage rating at least twice the maximum working voltage. For 16.8V batteries it the closest voltage rating is 35V, but 25V should also be ok in this case. Ceramic capacitor capacitance decreases with voltage.

![image](https://user-images.githubusercontent.com/1595938/193907714-0253aaee-54ce-4925-beda-827726d7e936.png)
https://www.murata.com/en-us/support/faqs/capacitor/ceramiccapacitor/char/0005

**Comment by AnishShr** [comment]
changed the 50uF capacitor with a parallel combination of 5 10uF capacitors (5 X10uF = 50uF)

**Comment by ReikoR** [comment]
10uF capacitance is bit too big for 0603 capacitors. 0603 10uF capacitors are not that common and cost more. In the lab we have 1206 capacitors. We can also order 0805 capacitors which cost about the same as 1206 ones. 

You should change 10uF capacitors to either 1206 or 0805 package.

**Comment by AnishShr** [comment]
changed the 10uF capacitors to 0805 package
