### ISSUE TITLE
Keep isolated sides completely separate

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#20]
There needs to be clear separation between isolated sides, that splits the board in two.

Illustrative image with some modifications. Taken from [this guide](https://www.ti.com/lit/an/slla284f/slla284f.pdf?ts=1664620687565):

![image](https://user-images.githubusercontent.com/1595938/193412347-e4857a48-caf2-475c-a716-99536826ed25.png)

**Comment by AnishShr** [comment]
should the space between the isolated sides be free from ground fill as well?

**Comment by ReikoR** [comment]
Yes, there should not be any copper.

**Comment by AnishShr** [comment]
Isolator's sides to be isolated are completely isolated (Not even copper pour in between)

**Comment by ReikoR** [comment]
Grounds should not extend past the isolators.

![image](https://user-images.githubusercontent.com/1595938/195159561-d71167b7-99ff-455f-9da7-11ce3dc34812.png)

**Comment by AnishShr** [comment]
GND and GND2 filled on both inner layers with ground not extending past the isolators
