### ISSUE TITLE
Mounting holes are too close to the edge

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#22]
![image](https://user-images.githubusercontent.com/1595938/193412743-dfbd2a64-ee25-4884-a6cd-45f460416a1c.png)

**Comment by AnishShr** [comment]
Mounting holes shifted a little inside.

**Comment by ReikoR** [comment]
Holes are still probably too close to the edges:
![image](https://user-images.githubusercontent.com/1595938/194123377-368c8256-39f7-4221-9c9a-757d28e24d00.png)

Also Typical M3 bolt head has a diameter of about 5.5mm. There should not be any tracks or components near the mounting holes that might be damaged by the bolt head:
![image](https://user-images.githubusercontent.com/1595938/194123979-97eed4bb-469d-4740-84f9-9ea209d82faf.png)

**Comment by AnishShr** [comment]
Mounting hole's external diameter is set to 6mm, and the hole to 3mm.
