### ISSUE TITLE
Add reverse voltage protection MOSFET to motor drivers power input

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#23]
More info:
https://ut-robotics.github.io/picr22-home/basketball_robot_guide/electronics/components.html#_reverse_voltage_protection

**Comment by AnishShr** [comment]
<img width="514" alt="BUK6Y10_pinout" src="https://user-images.githubusercontent.com/62991158/193660927-526c93cd-b813-43cc-b80d-c41c6e395c43.PNG">

For the reverse voltage protection MOSFET BUK6Y10, are the pins 1,2 and 3 internally connected? (Since all three are Source)

**Comment by ReikoR** [comment]
Yes, they are connected.

**Comment by AnishShr** [comment]
Added the reverse voltage protection MOSFET to Motor driver's input pin.

**Comment by ReikoR** [comment]
1. There is no need for multiple MOSFETs, 1 is enough.
![image](https://user-images.githubusercontent.com/1595938/195162249-c9ae8f8e-d488-4398-87e7-5bd0a484aab0.png)

2. I don't think that 1N53xxB diodes exist in 0603 package. You need to select a diode that we have in the lab (not sure if and what we have) or that can be ordered. For BUK6Y10 you probably won't need the diode, because the gate-source voltage rating is 20V, which is higher than the battery voltage.
![image](https://user-images.githubusercontent.com/1595938/195163234-79689df5-3921-4e11-89a0-53576717f557.png)

3. You definitely should not have 10-ohm resistor across battery voltage.
![image](https://user-images.githubusercontent.com/1595938/195163604-05da0f78-3efd-4bbf-9262-2bfbd999f8a9.png)

In the [guide](https://components101.com/articles/design-guide-pmos-mosfet-for-reverse-voltage-polarity-protection) they are used a a load. For the mainboard the load is the motors.
![image](https://user-images.githubusercontent.com/1595938/195163836-be183739-95c0-49dd-bbdd-e8d383419e82.png)

**Comment by AnishShr** [comment]
changed the connections as instructed with just one MOSFET.

changed the connections for the BUK6Y10. Removed the diode and 10 ohm resistors, with feedback resistors connected to FB pin, and bootstrap capacitor between SW and BST pin.
