### ISSUE TITLE
Use as wide as possible connections for high currents

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#24]
Motor driver outputs and power supply should use wider connections.

Based on Saturn PCB Toolkit a 0.4 mm wide track can carry 2.3A at 20 degree temperature rise:

![image](https://user-images.githubusercontent.com/1595938/193413545-0a4b5e78-12ac-49d8-a796-77dd6be2523e.png)

Motor drivers might output more current and power supply traces need to carry 3 times of that if drivers are connected in series.
I recommend having wide and short copper zones for high currents.

**Comment by AnishShr** [comment]
Motor driver's output with track width 0.5mm updated.

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/194131718-731147cb-f120-47c1-abe7-b8dee5142bb1.png)

It would be better if connections were shorter and wider.
Current pin headers are not a very good choice for connecting motor outputs. It would be better to create component with a SMD pad footprint large enough to allow wires to be soldered to it.

For example something like this:
![image](https://user-images.githubusercontent.com/1595938/194132386-9d8d67d5-aef3-4833-816f-471a0d47182f.png)

Small vias can be placed inside drivers pads for the shortest connections to power. Capacitors can be placed on the other side of the board below drivers.
![image](https://user-images.githubusercontent.com/1595938/194132205-ee30a84d-b088-4c04-af61-14d4c7c27cf8.png)

**Comment by AnishShr** [comment]
Track width for the motor driver's output lines have been set to the width of the motor driver's ouptut pad width.

**Comment by AnishShr** [comment]
changed the connectors making the connections short

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/195411657-59a65322-abde-4c42-b723-606257150597.png)

High current connections need to be wider.

Use copper zones and multiple small vias (0.2/0.45mm is the recommended smallest size by JLCPCB).

Rough example:
![image](https://user-images.githubusercontent.com/1595938/195416416-8d073851-f1b4-4c30-b76c-4ccdfa1aa7bc.png)

Driver outputs and V+ should also be connected with wide copper fills.

**Comment by AnishShr** [comment]
High current paths all connected with copper fills

**Comment by ReikoR** [comment]
1. Use solid pad connection for high currents:
![image](https://user-images.githubusercontent.com/1595938/195996643-206f5289-46bc-41b1-84a8-13ad8e9243a5.png)
![image](https://user-images.githubusercontent.com/1595938/195997371-877de25a-8591-43ae-bc7f-99cd7220ea84.png)
![image](https://user-images.githubusercontent.com/1595938/195996614-878fdb2f-c5cc-41ff-8032-e06b0c228acc.png)

2. Use multiple small vias instead of one larger via. Multiple small vias have smaller total inductance, higher current carrying capability and don't pull away the solder that easily when placed inside a pad.
![image](https://user-images.githubusercontent.com/1595938/195996676-3adbdb70-6e9a-4caf-a9f7-1a9e3973b734.png)

3. Drill diameter for small vias should be 0.2mm, otherwise the annual ring will be too narrow.
![image](https://user-images.githubusercontent.com/1595938/195996812-a2fccbb1-d99b-43d0-ba48-f539b13e552b.png)

4. Use larger pads for high currents. Current pads might be too small to solder wires to. Larger pads also are more robust. Smaller pads might break off the board. Putting multiple vias inside the pad would also help to make it mechanically more robust.
![image](https://user-images.githubusercontent.com/1595938/195997210-4aedae5c-4dbb-468b-a905-524f91120696.png)

5. I would also recommend placing VM capacitors directly below motor drivers to reduce inductance between drivers and capacitors.
![image](https://user-images.githubusercontent.com/1595938/196022780-7c099f09-ca3e-493b-9029-b61cb9e1da4c.png)

**Comment by AnishShr** [comment]
All power lines routed through copper fills

**Comment by ReikoR** [comment]
1. Reverse voltage protection MOSFET could be rotated to make VM polygon wider.
![image](https://user-images.githubusercontent.com/1595938/197379306-fa7b1a67-6a7e-4b75-ba5c-b34506d20772.png)
![image](https://user-images.githubusercontent.com/1595938/197379473-ea30e15a-9e94-4848-95d4-e1073f330224.png)
\
It would be even better if battery input (V+) pad could be placed on top of the MOSFET.
![image](https://user-images.githubusercontent.com/1595938/197379564-49dbe031-2b35-4117-9600-940f87c68f5c.png)

2. Motor driver VM capacitor could be better aligned with the driver pads.
![image](https://user-images.githubusercontent.com/1595938/197379802-c0ae3113-965e-4dd7-87e7-fb3359e11588.png)

3. There is no need to place vias inside pads for motor driver configuration pins. This will make soldering harder.
![image](https://user-images.githubusercontent.com/1595938/197379916-19353ef0-7b05-40c2-9236-54fa008433b7.png)
\
Something like this should be enough:
![image](https://user-images.githubusercontent.com/1595938/197379971-b28c84bf-66a1-4e5c-b4ea-6257d95ac3fe.png)

**Comment by AnishShr** [comment]
<img width="346" alt="Issue_PCB" src="https://user-images.githubusercontent.com/62991158/197388164-e578b2ff-7e80-4cfe-9167-6ff5766cecab.PNG">

How can we get rid of this issue? The copper fill clearance is set to 0.25 mm, but the fill has a clearance of 0.1016mm only in one of the edges.

**Comment by ReikoR** [comment]
You should use different priority levels for adjacent zones. Then the zones are filled in an order and clearance between them is automatically kept.
![image](https://user-images.githubusercontent.com/1595938/197388377-8060ef44-2475-4863-a998-27a37d4427dd.png)

**Comment by AnishShr** [comment]
<img width="937" alt="Issue_PCB2" src="https://user-images.githubusercontent.com/62991158/197389855-d7222957-9026-415e-b8b6-72272c3b60dc.PNG">
Is this warning fired because 'VM' is present in only one layer?

**Comment by ReikoR** [comment]
Yes

**Comment by AnishShr** [comment]
So shall I copper fill on the other layer as well? Or what shall I do?

**Comment by ReikoR** [comment]
Just remove those vias, since they are not connecting to anything on other layers.

**Comment by AnishShr** [comment]
These vias also include the ones in the decoupling capacitors. Should I remove them as well?

**Comment by ReikoR** [comment]
If you mean the ones connected to MCU VDDA, then yes.

**Comment by AnishShr** [comment]
unnecessary vias removed and power routed via copper fills and usage of multiple small vias where necessary

**Comment by ReikoR** [comment]
nSLEEP trace on bottom layer creates huge gap inside VM copper fill:
![image](https://user-images.githubusercontent.com/1595938/197856943-f98fdbc1-c998-4ec8-898c-9f93a79d25e6.png)

nSLEEP trace should be mostly routed on top layer to avoid it.

**Comment by AnishShr** [comment]
Most part of the nSleep trace routed in front copper making wise copper fills for VM

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/198085389-bdb50272-2661-4c5e-8060-24d543d462e7.png)

Rotating the reverse voltage protection MOSFET would help to improve current paths:
![image](https://user-images.githubusercontent.com/1595938/198086051-fdaeb842-79dc-48db-a78f-c83e220bfc1f.png)

**Comment by AnishShr** [comment]
MOSFET rotated and shifted to provide better current distribution path as instructed.

**Comment by ReikoR** [comment]
MOSFET should not moved too much to the center of the board. Having signal traces close to each other will cause more noise on them.

![image](https://user-images.githubusercontent.com/1595938/198378417-fc9350bc-04df-4712-bdb0-b2a111bcef62.png)

**Comment by AnishShr** [comment]
MOSFET moved away from other traces

**Comment by ReikoR** [comment]
You should also route tracks straighter and with more spacing between them. Noise on a trace from an adjacent trace is bigger when tracer are closer to each other or are close for longer. Running traces parallel next to each other should be minimised.
![image](https://user-images.githubusercontent.com/1595938/198830315-3fea658d-6cd4-4f81-a639-5a750462a2f6.png)
![image](https://user-images.githubusercontent.com/1595938/198830484-e27acffe-98e4-4bce-8c5c-d65e7254fae5.png)

**Comment by AnishShr** [comment]
Spacing between traces increased
