### ISSUE TITLE
Prefer 0603 passive components

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#25]
Most of the passive components available in the lab are in 0603 package.
If you don't want or need to save board space, then it would be better to use 0603 for most of the passive components.

**Comment by AnishShr** [comment]
All passive component's footprint updated to 0603 package.

**Comment by AnishShr** [comment]
All passive components changed to the 0603 package

**Comment by AnishShr** [comment]
apart from 10uF capacitors, all other passive device changed to 0603 package
