### ISSUE TITLE
Use switching regulator instead of linear regulator for servo power

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#26]
Linear regulators are too inefficient for higher currents.

We have these components available in the lab:

- XTPS62933DRLR (TPS62933 buck converter)
- SRP6060FA-5R6M (Inductor 5.6uH 10A)

You can use TI WEBENCH to get recommended designs for TI components:
https://webench.ti.com/power-designer/switching-regulator

**Comment by AnishShr** [comment]
TPS62933 buck added for powering the servo

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/194134701-b6bdc2d9-21b1-4610-9773-440b6284628e.png)
1. On the schematic you have TPS62932, not TPS62933.

2. Pinout is incorrect. Correct pinout from datasheet:
![image](https://user-images.githubusercontent.com/1595938/194135130-1da53730-a6b6-4ce4-a28b-457d5aecee5b.png)

3. Power inductor needs to connected to SW pin, not a ferrite bead. We have SRP6060FA-5R6M inductors, which are suitable.
![image](https://user-images.githubusercontent.com/1595938/194135372-63058f99-a1ce-46b7-b4ad-8cfe9e9573dc.png)

4. Switching regulator and all other components connected to the motors power should be on the other side of the isolators. PCB needs to be clearly divided into two isolated sides.
![image](https://user-images.githubusercontent.com/1595938/194136797-14f1e69b-43b1-4b06-af05-4580581eb23b.png)

**Comment by AnishShr** [comment]
The footprint for ferritebead changed to indcutor. And the isolators have been placed between two different power sources, dividing the PCB into two parts in regard to the power source.

**Comment by ReikoR** [comment]
1. Bootstrap capacitor needs to be connected between BST and SW pins. SW pin needs to be connected to inductor.
![image](https://user-images.githubusercontent.com/1595938/195166184-4497728f-5479-4674-8491-1ba56dfffa0b.png)

2. Feedback resistors need to connect to FB pin.
![image](https://user-images.githubusercontent.com/1595938/195166074-24f7f404-08ed-41dc-96be-0b2518e1e0da.png)

**Comment by AnishShr** [comment]
Changed the connection schematic for TPS62933.

Bootstrap capacitor connected between BST and SW pins. SW pin connected to inductor.

Feedback resistors connected to FB pin.

**Comment by ReikoR** [comment]
1. SRP6060FA-5R6M has inductance of 5.6uH, not 7.6uH.
![image](https://user-images.githubusercontent.com/1595938/195392946-093d8d7a-81ae-4d86-b8a9-b6929d6b82d3.png)

2. TPS62933 VIN should be connected to VM, not V+, to also protect the regulator from reverse voltage.
![image](https://user-images.githubusercontent.com/1595938/195393071-f0eff385-0145-49ae-9f8e-6844654de71c.png)
![image](https://user-images.githubusercontent.com/1595938/195393010-6eb73a04-622f-4e1d-bb30-4c8f60d51646.png)

3. 100uF 10V+ 0603 capacitors do not exist or are not available.
![image](https://user-images.githubusercontent.com/1595938/195395338-690fbfae-d318-411c-9736-898775f9ae04.png)
Smallest available size seems to be 1206:
https://www.mouser.ee/c/passive-components/capacitors/mlccs/multilayer-ceramic-capacitors-mlcc-smd-smt/?capacitance=100%20uF&voltage%20rating%20dc=10%20VDC~~50%20VDC&rp=passive-components%2Fcapacitors%2Fmlccs%2Fmultilayer-ceramic-capacitors-mlcc-smd-smt%7C~Voltage%20Rating%20DC&sort=pricing

4. Additional 5V linear regulator is not needed. Isolators can be powered from switching regulator.
![image](https://user-images.githubusercontent.com/1595938/195406832-9decbca4-4074-470a-ae3f-f3ee3ee5509c.png)

**Comment by AnishShr** [comment]
Linear regulator removed and isolators powered by the switching regulator

**Comment by ReikoR** [comment]
1. Inductance is still incorrect.
![image](https://user-images.githubusercontent.com/1595938/195392946-093d8d7a-81ae-4d86-b8a9-b6929d6b82d3.png)

2. Try to follow layout guidelines in the [TPS62933 datasheet](https://www.ti.com/lit/ds/symlink/tps62933.pdf).

For example:
> Place the inductor, input and output capacitors, and the IC on the same layer.

Currently regulator and inductor are on the top layer and capacitors on the bottom layer.
![image](https://user-images.githubusercontent.com/1595938/195994622-91de3480-4ad8-4309-ab31-260bd490aadb.png)

> Place the input and output capacitors as close as possible to the IC.

Output capacitor is far away.
![image](https://user-images.githubusercontent.com/1595938/195994737-61632bfc-8e0a-4cd6-ba91-54cd0d8389dc.png)

> The VIN and GND traces must be as wide as possible and provide sufficient vias on them to minimize trace impedance. The wide areas are also of advantage from the view point of heat dissipation.
Keep the SW trace as physically short and wide as practical to minimize radiated emissions.

Current traces/connections are narrow and could probably be shorter. Use multiple small vias (0.2/0.45) for VIN, GND, +5VD for lower inductance. In general multiple smaller vias work better than one larger via for reducing inductance and having higher current carrying capability.

3. It would also be better to have servo connector near the regulator output.
![image](https://user-images.githubusercontent.com/1595938/195995430-7aa53e8b-0d43-4870-8257-c24c05aa8bb4.png)

4.  In regards of more general layout, having isolators on the top layer and switching regulator components on the bottom side might improve the layout. Right now every signals needs a via on both sides of the isolators.
![image](https://user-images.githubusercontent.com/1595938/195995441-380ecd87-57a2-4e53-a136-5f2ff93d2bed.png)

**Comment by AnishShr** [comment]
Inductor connection updated, with input/output capacitors placed close.

Also, the power lines are routed through copper fills, each pad with multiple small vias.

**Comment by ReikoR** [comment]
1. Inductance value is still incorrect.
![image](https://user-images.githubusercontent.com/1595938/195392946-093d8d7a-81ae-4d86-b8a9-b6929d6b82d3.png)

2. From [datasheet](https://www.ti.com/lit/ds/symlink/tps62933.pdf):
> Place the feedback divider as close as possible to the FB pin. A > 10-mil width trace is recommended for heat dissipation. Connect a separate VOUT trace to the upper feedback resistor. Place the voltage feedback loop away from the high-voltage switching trace. The voltage feedback loop preferably has ground shield.

It's better to have separate 5V feedback trace that is shielded with ground vias. Running it on opposite layer (top in this case) should help to shield it more.
![image](https://user-images.githubusercontent.com/1595938/197378406-ce5c38b3-3884-4f5b-b176-268afa910390.png)

3. All the vias marked with a yellow arrow do not connect to any other layers and should be removed:
![image](https://user-images.githubusercontent.com/1595938/197378508-22f6dedf-2c82-42b0-89f5-4177b497a73f.png)

4. There is only 1 ground via:
![image](https://user-images.githubusercontent.com/1595938/197378983-f00f92f3-46f9-430b-b043-c8b7f9942bc1.png)
\
Something like this would be better:
![image](https://user-images.githubusercontent.com/1595938/197379179-240983c2-4c5f-4d6e-bc33-f4d7f3104585.png)
I rotated and moved the capacitors a bit and added copper fill on bottom layer and multiple ground vias.

**Comment by AnishShr** [comment]
8.8 uH Inductor placed with power routed through copper fills and use of vias

**Comment by ReikoR** [comment]
1. SRP6060FA-5R6M is a 5.6uH inductor, not 6.8uH.
![image](https://user-images.githubusercontent.com/1595938/197843002-dcea176f-aaed-4f8c-9c2d-d6096a573f29.png)

2. 5V feedback trace is quite close to driver signal traces.
![image](https://user-images.githubusercontent.com/1595938/197845360-290428c2-43ab-40df-a837-0409b3950cbc.png)
\
It would be better to increase distance between traces and add ground vias for shielding:
![image](https://user-images.githubusercontent.com/1595938/197846886-2edf301f-a7a2-4565-a653-a9371a039105.png)

3. 5V feedback should only be connected with trace on top layer and not with copper fill on bottom layer:
![image](https://user-images.githubusercontent.com/1595938/197847223-0c2955ac-e0da-40e7-8f53-4f64bfc9291e.png)

4.  FB trace is very close to the inductor.
![image](https://user-images.githubusercontent.com/1595938/197848386-77b6f730-a4a3-47d0-a9e7-3e979670ca21.png)
\
Try to follow layout recommendations in the datasheet:
![image](https://user-images.githubusercontent.com/1595938/197848574-3466ece1-27a0-4c00-b818-8e0724c1b291.png)
\
Something like this might be better:
![image](https://user-images.githubusercontent.com/1595938/197855682-f1cde1b5-9f07-4987-9108-329be71cb365.png)

**Comment by AnishShr** [comment]
Changed the layout and added GND vias across one side of the 5V trace.
