### ISSUE TITLE
[Mechanics] Check direction of thrower motor wires

### ISSUE THREAD

**Issue by maidlam** [ut-robotics/picr22-team-saga#3]
In the current model, it seems like the thrower motor wires will come out into the ramp.
I think the wire hole is in the wrong position in the model.
Verify the actual location of the wires on your physical motor and add a box to represent the wires.

![pilt](https://user-images.githubusercontent.com/32770145/191021213-ba071b7f-d02f-4b76-af3d-3248ecf061e3.png)

**Comment by georgsnarbuts** [comment]
I compared this cad model to our actual motor and the wires seem to be located in the same place so i rotated the motor by 180 degrees, so the wires could point outwards. Is this good?
