### ISSUE TITLE
Place ESD protection as close as possible to USB connector

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#30]
TVS diodes (diode arrays) should be placed as close as possible to connectors to prevent ESD from reaching to any of the components.

![image](https://user-images.githubusercontent.com/1595938/195408281-61247952-8529-47b2-90f1-abd2937b41f5.png)

**Comment by AnishShr** [comment]
ESD protection placed close to the USB

**Comment by ReikoR** [comment]
ESD protection could be even closer, but it might be good enough.
![image](https://user-images.githubusercontent.com/1595938/197377806-2b361909-7839-4dfa-ab32-937e0662233b.png)
