### ISSUE TITLE
Fix DRC errors (and warnings if possible)

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#31]
Use **Inspect -> Design Rule Checker**

Unconnected nets are the probably the biggest problem:
![image](https://user-images.githubusercontent.com/1595938/195409652-2d215eb4-cb1c-4653-893c-d562e951066b.png)

Unconnected nets can also be seen without running DRC.
![image](https://user-images.githubusercontent.com/1595938/195409868-6e189fb8-a7cf-4a76-be8e-5ab300e08f4f.png)

**Comment by AnishShr** [comment]
DRC errors fixed, except few(Not an error actually)

Please have a look

**Comment by ReikoR** [comment]
There is a clear unconned +3.3V net:
![image](https://user-images.githubusercontent.com/1595938/195999878-8e897b6d-25bd-4712-b3a4-dd024220934a.png)

**Comment by AnishShr** [comment]
The unconnected 3.3V nets both are connected to two 3.3V pins of the microcontroller, which are internally connected. Is it necessary to connect them externally?

**Comment by ReikoR** [comment]
Power should never be routed through components. Component might not have enough current carrying capability and all the noises add together if current paths are shared between components. Ideally power should be routed from single point (power source) to each component through separate (straight) path.

It would probably be better to change bottom layer copper fill from GND to +3.3V and route most of the signals on top layer to reduce gaps in the +3.3V copper. There already are 2 GND copper fills on internal layers.

**Comment by ReikoR** [comment]
There are still a lot of errors that can be fixed.

**Comment by AnishShr** [comment]
DRC errors fixed (Few warnings left: especially for mounting holes vias)
