### ISSUE TITLE
Improve USB signal routing

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#32]
Current routing:
![image](https://user-images.githubusercontent.com/1595938/195998294-3c7ae91d-67d6-4a36-a6f3-29bb1c58ab19.png)

1. USB data signals are a 90-ohm differential pair and should be routed on the PCB to match that.
2. Using vias should be avoided for differential pairs or if not possible, should be kept symmetric in both signals in a pair, so that same amount of vias is used and at the same locations in both signal traces.
3. Traces should also be as symmetric and straight as possible. 
4. Differential signal routing should usually prioritised over routing other (single-ended) signals and power.

JLCPCB has [impedance calculator](https://cart.jlcpcb.com/impedanceCalculation) for their stackups.
![image](https://user-images.githubusercontent.com/1595938/195998438-d6d7204d-f072-4ca0-9735-d00d4c317b55.png)

We'll use JLC3313 stackup, because it has smaller gap between layers, which helps to improve signal integrity because electric fields (between signal and reference [usually GND] layer) of different signals interact less with each other, since electric fields don't spread out as much.

8 mil gap and 6.03 mil trace widths are close enough to 2mm and 1.5mm, so those can be used.

Differential pair (DP) width and gap can be specified in the Board Setup.
![image](https://user-images.githubusercontent.com/1595938/195998174-e10d2b3f-78a1-45c2-ac40-1904a27baa45.png)

Some board constraints should also be adjusted.
![image](https://user-images.githubusercontent.com/1595938/195999043-066a4ddb-bbd1-462d-92e0-536e2981aa2e.png)

Default shortcut for differential pair routing is 6.
![image](https://user-images.githubusercontent.com/1595938/195999090-50dd95a0-4f8a-45a2-97c1-40554787c786.png)

**Comment by AnishShr** [comment]
Should the differential pair be symmetric for connections to the ESD protection as well, or is it ok if the differential pair routing is symmetric only from the microcontroller pins to the SUB?

**Comment by ReikoR** [comment]
Ideally differential pair should be symmetric everywhere. ESD protection should be aligned so that the signals can be routed underneath the ESD protection component.

Example layout of ESD protection component with same pinout as CM1223-02SO:
![image](https://user-images.githubusercontent.com/1595938/196022135-d4193eb9-ac46-420e-b964-d709f3804cc2.png)

Image taken from here:
https://www.we-online.com/catalog/media/o109030v410%20AppNotes_ANP002_TheProtectionOfUSB20Applications_EN.pdf

**Comment by AnishShr** [comment]
Differential pair routed

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/197377393-dc404318-c1b3-45c8-be62-fb759936fa9f.png)

USB differential signals can be more straight and symmetric.

KiCad differential pair routing does not work very well, so some manual routing and moving of tracks is probably needed.

Improved result can look something like this:
![image](https://user-images.githubusercontent.com/1595938/197377682-c4a6ff23-fcbf-446d-b4c9-4a0fb85f1ff2.png)

**Comment by AnishShr** [comment]
Differential pair for USB routed appropriately (please check)

**Comment by ReikoR** [comment]
1. USB signal traces do not have correct width:
![image](https://user-images.githubusercontent.com/1595938/197836960-d5bc7f65-4372-40b4-9566-0ee227b64854.png)

2. I'm not sure if there are manufacturing issues with it, but it's probably good idea to avoid sharp (internal) corners:
![image](https://user-images.githubusercontent.com/1595938/197837199-763a45f9-0f13-4f48-a96a-530170a14aa5.png)
\
Connect straight to pads if possible:
![image](https://user-images.githubusercontent.com/1595938/197839911-fa16b502-134c-42d3-9e38-2b00cee6835e.png)
\
Or move traces slightly away from the pads:
![image](https://user-images.githubusercontent.com/1595938/197840137-5c08adfc-2ccb-4521-85ed-e22758ce2e8b.png)

**Comment by AnishShr** [comment]
Traces palces straight to the USB pads in uC.

**Comment by ReikoR** [comment]
USB signal trace width is still incorrect.

**Comment by AnishShr** [comment]
USB signal trace changed to 0.153 mm

**Comment by ReikoR** [comment]
![image](https://user-images.githubusercontent.com/1595938/198354155-9d3d9b26-d4f2-4cea-9ea7-3f376b27944c.png)

Spacing between traces needs to be 0.2mm (not 0.25mm) to have correct differential impedance.

**Comment by AnishShr** [comment]
spacing between the USB differential traces maintained to 0.2 mm
