### ISSUE TITLE
Place decoupling capacitors as close as possible to power pins

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#33]
![image](https://user-images.githubusercontent.com/1595938/195999735-a2a2f4c4-089d-4a5e-b219-e4d95e6cf984.png)

![image](https://user-images.githubusercontent.com/1595938/195999789-e3056eee-8098-4730-b1b0-aa74dcb2b94a.png)

**Comment by AnishShr** [comment]
Decoupling capacitors places close to the respective components

**Comment by ReikoR** [comment]
MCU decoupling capacitors are incorrectly placed or can be closer to MCU pins:
![image](https://user-images.githubusercontent.com/1595938/197377275-9b8198f2-cf60-4d7f-9e27-cce3bcc9aa6a.png)

**Comment by AnishShr** [comment]
Decoupling capacitors placed closer and in correct place

**Comment by ReikoR** [comment]
1. Each power pin should have one 100nF capacitor close to it:
![image](https://user-images.githubusercontent.com/1595938/197841293-b6779738-2e88-450a-b32d-8048f710f73b.png)

2. Decoupling capacitors should be connected on the same layer with wide traces. Connecting them through bottom layer with vias will have worse inductance which decreases the usefulness of the capacitors.
![image](https://user-images.githubusercontent.com/1595938/197841951-d0b194c8-f377-42ef-8601-8ddc9b85e321.png)
![image](https://user-images.githubusercontent.com/1595938/197842304-c69c4b85-2d76-4e61-bd45-4823b2801dcb.png)

**Comment by AnishShr** [comment]
All decoupling capacitors connected with wide traces in same layer

**Comment by ReikoR** [comment]
1 uF capacitor on the schematic is meant for analog supply filtering:
![image](https://user-images.githubusercontent.com/1595938/198093793-368729db-17c3-49a1-9967-9368da54d21a.png)
![image](https://user-images.githubusercontent.com/1595938/198093572-e938ff69-edbd-474b-90a7-b53507c04add.png)

**Comment by AnishShr** [comment]
1 uF capacitor placed in appropriate position.
