### ISSUE TITLE
Unnecessary vias

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#34]
1. There are a lot of vias connected only on 1 layer. This can also be checked with DRC.
![image](https://user-images.githubusercontent.com/1595938/197376585-d5d38252-eb4a-44ba-a4e8-07518b9e164f.png)

2. You don't need that many vias for low currents. Up to 2 per decoupling capacitor is enough. Adding to many vias inside pads can make soldering hard.
![image](https://user-images.githubusercontent.com/1595938/197376754-f4bba2b7-7e32-4b26-9cf8-9a6579ce0b30.png)
\
Something like this would be good for most decoupling capacitors:
![image](https://user-images.githubusercontent.com/1595938/197377056-076c2584-868a-4be7-a9ea-3723ddc1be40.png)
Keeping +3.3V and GND vias close to each other makes sure that electric field between them spread out less.

3. Programmer connector does not have any high currents. 1 via per pin is enough.
![image](https://user-images.githubusercontent.com/1595938/197377172-d86185c2-9723-4bad-95df-aaf364524e2e.png)

**Comment by AnishShr** [comment]
Unnecessary vias removed

**Comment by AnishShr** [comment]
Can we put just one via in the Isolators pins and decoupling capacitors?

**Comment by ReikoR** [comment]
1. Another thing to avoid are wide gaps in copper fills created by vias that are close to each other:
![image](https://user-images.githubusercontent.com/1595938/198095968-030394a8-2d37-48a0-9b49-9347db6ed2e1.png)
\
More space should be added between vias:
![image](https://user-images.githubusercontent.com/1595938/198096573-9db5f2fa-e273-42c5-ba3a-950d4b57c11d.png)

2. Use same small size via everywhere on the board:
![image](https://user-images.githubusercontent.com/1595938/198097009-4627e896-31e9-4812-ad19-642b85a1f6c8.png)

**Comment by AnishShr** [comment]
Uniform via size maintained all over the PCB with gaps maintained as well.
