### ISSUE TITLE
Incorrect servo pinout

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#35]
![image](https://user-images.githubusercontent.com/1595938/198097304-d2991b72-39ac-444a-9913-5fe3c7f504a3.png)

Correct pinout is:
1. GND
2. 5V
3. PWM

![image](https://user-images.githubusercontent.com/1595938/198097440-c396782c-8069-4d11-a9e2-86946f1fe8b2.png)
https://dronebotworkshop.com/servo-motors-with-arduino/

**Comment by AnishShr** [comment]
Connector for servo motor in correct pinout orientation updated
