### ISSUE TITLE
Silkscreen text too small

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#36]
![image](https://user-images.githubusercontent.com/1595938/198099572-9ef115ef-1c13-431e-8077-4123e88d6854.png)

JLCPCB recommended minimums are here (under Legend section):
https://jlcpcb.com/capabilities/pcb-capabilities

> Minimum Line Width: 0.153mm
> Minimum text height: 1.0mm

**Comment by AnishShr** [comment]
Silkscreen text updated: Text Height=1.0mm; Text Width=1.0mm; Text Thickness = 0.2mm
