### ISSUE TITLE
Silkscreen improvements

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#38]
1. Avoid placing reference designators under components. They should be visible when components are on the board.
![image](https://user-images.githubusercontent.com/1595938/198358241-bab16a50-dc09-4b46-a0b6-7613a6afe650.png)

2. Try to use same rotation for adjacent text/reference designator for easier readability.
![image](https://user-images.githubusercontent.com/1595938/198360882-92b41922-57af-4e83-8c73-049ab81d68ec.png)

3. For driver output pads and power input pads it would be more useful to remove/hide reference designators and use custom text that is more descriptive.
![image](https://user-images.githubusercontent.com/1595938/198375426-3b713667-b408-4ba0-9c9a-2c01d42840a6.png)
![image](https://user-images.githubusercontent.com/1595938/198375462-ad03b8af-08fa-4355-9e5f-acc65e951742.png)
\
Similar to connectors.
![image](https://user-images.githubusercontent.com/1595938/198375658-58b47a89-faa2-44c2-ac64-cc5f6da54192.png)

**Comment by AnishShr** [comment]
Labels for components oriented in same direction and outside the component space.

For Motor driver output pads: OUT+ and OUT- Labels are placed for each driver outputs.
For Servo pins, labels: Signal->S, 5V->+, GND->- have been placed
For Battery inputs, Battery+->BAT+, Battery- -> BAT- have been placed
For Thrower Power Output pads, Thrower+ -> THRWR+, Thrower- -> THRWR- have been placed

**Comment by AnishShr** [comment]
<img width="392" alt="PCB_3D_front" src="https://user-images.githubusercontent.com/62991158/198505463-3759afb6-4503-47cd-99d1-d10fc8f98a0e.PNG">
<img width="308" alt="PCB_3D_back" src="https://user-images.githubusercontent.com/62991158/198505482-94f2af6e-1ad4-4509-b0b6-daa329b9e8e6.PNG">


Labels renamed something like this
