### ISSUE TITLE
Mounting hole and board outline coordinates

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#40]
![image](https://user-images.githubusercontent.com/1595938/198944832-04ae7d74-5a9b-4395-84ad-870c9d6df0ae.png)

It would be easier to add mounting holes in robot's mechanical design if PCB mounting holes were on a 1mm or 0.5mm grid.

Board outline (Edge Cuts rectangle) also has weird dimensions:
![image](https://user-images.githubusercontent.com/1595938/198945140-265d1714-fe0a-4744-98a3-7d71d143be96.png)

**Comment by AnishShr** [comment]
board cutouts and mounting holes aligned in a 0.5mm grid size with proper dimensions.
