### ISSUE TITLE
Create Gerber X2 files

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#41]
Create Gerber X2 layer and drill files and commit them to repository for ordering the manufacturing.

**Comment by AnishShr** [comment]
Gerber files with drill files generated.

**Comment by AnishShr** [comment]
<img width="603" alt="JLCPCB_boards" src="https://user-images.githubusercontent.com/62991158/198996585-c924888d-0883-4a63-864f-d1572cb82b54.PNG">
<img width="622" alt="JLCPCB_layer_stack" src="https://user-images.githubusercontent.com/62991158/198996589-89493a37-6f1d-45ec-b032-483d0138596b.PNG">

The required gerber files are pushed to the repo with a compressed zip file as JLCPCB expects. The layer stack should be as it is in the picture. Please have a look.

**Comment by ReikoR** [comment]
PCBs have been ordered.
