### ISSUE TITLE
Mainboard documentation

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#60]
1. _"There is a SUB connector in the board"_
\
SUB -> USB

2. Specify what type and how many motors the board can control and what is the input voltage and output current limits.

3. Programmer pinout is incorrect.
\
![image](https://user-images.githubusercontent.com/1595938/212484465-3eb9acb1-1aa8-41f1-8424-418a9cb72530.png)

4. Thrower connector has 4 pins.
\
![image](https://user-images.githubusercontent.com/1595938/212484533-cf68456b-47f5-409d-8890-e3cac3c714ce.png)

5. Add reference designators to connector pinouts.

6. Typos/misspellings:
    - regualtor
    - motros
    - sneds
    - Conenctors

**Comment by AnishShr** [comment]
Errors corrected.

**Comment by ReikoR** [comment]
1. _"The board can controlcontrol 3 DC motors."_
\
controlcontrol -> control
\
Specify which type of DC motors. Brushed or brushless.

2. The output current of the Voltage regulator is about 2.77 A.
\
Do you mean motor driver, instead of voltage regulator?
Also 2.77A is not correct if 3k IPROPI resistor is used.

3. All encoder connector pinouts are written as Motor1.
\
![image](https://user-images.githubusercontent.com/1595938/212552280-651647b1-887b-4a21-9dc8-a79e642e9cf9.png)
\
Encoder connector pinouts can be grouped together, since the pinouts are the same.

4. README.asciidoc needs to be in `electronics` directory as is written here:
https://ut-robotics.github.io/picr22-home/team_documentation_requirements.html

**Comment by AnishShr** [comment]
3.3k resistor is used in IPROPI pin, so the output is around 2.77 A. This is explained in the updated file.

**Comment by AnishShr** [comment]
All changes made as requested and pushed to repo.
