### ISSUE TITLE
[Mechanics] Thrower assembly too wide

### ISSUE THREAD

**Issue by Akustav** [ut-robotics/picr22-team-saga#7]
The thrower assembly is 0.4mm too wide and tabs clip into the bottom plate:

![image](https://user-images.githubusercontent.com/5435954/192096569-54daaf98-37f7-455d-8aed-0f6c3fa629ec.png)

**Comment by maidlam** [comment]
Current distance between thrower walls is 50,40 mm.
The top and bottom plate have different distances for the holes for the walls.

![Fusion360_2022-09-30_22-02-00](https://user-images.githubusercontent.com/32770145/193339210-8ae27e37-a3eb-498d-b12b-b1a7a7915004.png)
![Fusion360_2022-09-30_22-02-30](https://user-images.githubusercontent.com/32770145/193339211-5fe76d96-a3a5-4f6a-89b1-c76387887513.png)

The holes in the top plate are sketched separately, while the bottom plate uses a pattern to make the holes, that's where the offset might be coming from.

![pilt](https://user-images.githubusercontent.com/32770145/193341666-a5dfe9cb-f4e2-4689-a144-648485d7b2c3.png)

Don't know if the holes on the actual robot might have been modified, or the thrower was just jammed in.

**Comment by Akustav** [comment]
I think we had one robot that had alignment issues due to a oversight in the review. I think it was milled out like that. I think we modified the thrower tabs to accommodate the thrower. Seems like a small issue, overall.
