### ISSUE TITLE
Pull-up resistor on USB D+ line is not needed

### ISSUE THREAD

**Issue by ReikoR** [ut-robotics/picr22-team-saga#9]
SMT32G441 has embedded pull-up resistor.

From [datasheet](https://www.st.com/resource/en/datasheet/stm32g441kb.pdf):
> **3.35 Universal serial bus (USB)**
> ... The internal USB PHY supports USB FS signaling, embedded DP pull-up and ...

More information is available under **45 Universal serial bus full-speed device interface (USB)** in [reference manual](https://www.st.com/resource/en/reference_manual/rm0440-stm32g4-series-advanced-armbased-32bit-mcus-stmicroelectronics.pdf).

**Comment by AnishShr** [comment]
The pull up resistor has been removed. Pushed new design in the github repository: https://github.com/ut-robotics/picr22-team-saga/tree/electronics
